apiVersion: "etcd.database.canonical.com/v1beta3"
kind: "EtcdCluster"
metadata:
  name: "example-etcd-cluster"
  # Adding this annotation make this cluster managed by clusterwide operators
  # namespaced operators ignore it
  annotations:
    etcd.database.canonical.com/scope: clusterwide
spec:
  size: 3
  version: "3.2.13"
