
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: mayastor
  name: etcd-operator-role
rules:
- apiGroups:
  - etcd.database.canonical.com
  resources:
  - etcdclusters
  - etcdbackups
  - etcdrestores
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - "*"
# The following permissions can be removed if not using S3 backup and TLS
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: mayastor
  name: etcd-operator-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: etcd-operator-cluster-role
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - list
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: mayastor
  name: etcd-operator-role-binding
subjects:
- kind: ServiceAccount
  name: etcd-operator-sa
  namespace: mayastor
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: etcd-operator-role
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: etcd-operator-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: etcd-operator-sa
  namespace: mayastor
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: etcd-operator-cluster-role
