apiVersion: etcd.database.canonical.com/v1beta3
kind: EtcdCluster
metadata:
  name: mayastor-etcd
  namespace: mayastor
spec:
  size: 3
  limitSizeToMaxReadyNodes: true
  version: "3.5.4"
  pod:
    # hostPathVolume: /var/snap/microk8s/common/default-storage/mayastor-etcd/$NAME
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: etcd_cluster
              operator: In
              values: [mayastor-etcd]
          topologyKey: kubernetes.io/hostname
